apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DEBUG: {{ .Values.config.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.config.ALLOWED_HOSTS | quote }}
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}