replicaCount: 1

image:
  repository: ghcr.io/alexvic-che/devops-test-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

config:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

secret:
  DJANGO_SECRET_KEY: "devops-test-secret-key"